language: go

go:
  - "1.11.x"

sudo: false

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script:
  - go vet ./...
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  - provider: script
#    script: bash ./assets/scripts/deploy.sh
    script: bash $TRAVIS_BUILD_DIR/make build && bash $TRAVIS_BUILD_DIR/make update
    on:
      branch: master