language: go

go:
  - "1.11.x"
  - master

# Only clone the most recent commit
git:
  depth: 1

notifications:
  email: false

before_script:
  - go vet ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)