language: go

go:
  - "1.11.x"
  - master

git:
  depth: 1

notifications:
  email: false

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)