language: go

go:
  - "1.11.x"
  - master

sudo: false

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script:
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)