language: go

go:
  - "1.11.x"
  - master

sudo: false

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script:
  - go vet ./...
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: lambda
  function_name: "payments"
  region: "us-west-2"
  role: "arn:aws:iam::149764127702:role/service-role/payments"
  runtime: "go1.x"
  module_name: ""
  handler_name: "main"
