
[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "~1.3.0"

#[[constraint]]
#  name = "github.com/pkg/errors"
#  version = "~0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.3.0"